---
# tasks file for hephy.cvmfs-client
- name: Load OS specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Enable CVMFS repository
  include_tasks: cvmfs-yumrepo.yml
  when: cvmfs_manage_yumrepo

- name: Install cvmfs
  package:
    name: cvmfs
    state: installed

- name: Create /cvmfs
  file:
    name: /cvmfs
    state: directory

- name: Create CVMFS user and group
  block:
    - name: Create group
      group:
        name: cvmfs
        system: true
    - name: Create user
      user:
        name: cvmfs
        group: cvmfs
        system: true
        home: /var/lib/cvmfs
        shell: /sbin/nologin
        comment: "CernVM-FS service account"
  when: cvmfs_manage_cvmfs_user and ansible_virtualization_type != 'docker'

- name: Set permisson on cache
  file:
    name: "{{ cvmfs_cache_base }}"
    owner: cvmfs
    group: cvmfs
    mode: 0700
    setype: cvmfs_cache_t


- name: Get size of CVMFS partition
  set_fact:
    __cvmfs_partition_size: "{{ ansible_mounts | json_query(jq) }}"
  vars:
    jq: "[?mount=='{{ cvmfs_cache_base }}'].size_total"
  when: cvmfs_quota_limit <= 0

- name: Fail in case the partition size cannot be determined
  fail:
    msg: "Cannot determine size of partition for mount point {{ cvmfs_cache_base }}"
  when: cvmfs_quota_limit <= 0 and __cvmfs_partition_size | length  == 0

- name: Configure CVMFS
  template:
    src: default.local.j2
    dest: /etc/cvmfs/default.local

- name: Configure autofs
  block:
    - name: Add cvmfs to /etc/auto.master
      lineinfile:
        path: /etc/auto.master
        regexp: "^/cvmfs"
        line: "/cvmfs  program:/etc/auto.cvmfs"
      notify: Restart autofs
    - name: Start autofs
      service:
        name: autofs
        enabled: true
        state: started
  when: cvmfs_manage_autofs and ansible_virtualization_type != 'docker'

- name: Configure respositories
  template:
    src: repository.local.j2
    dest: "/etc/cvmfs/config.d/{{ repository.name }}.local"
  loop: "{{ cvmfs_repositories }}"
  loop_control:
    loop_var: repository

- name: Configure domains
  template:
    src: repository.local.j2
    dest: "/etc/cvmfs/domain.d/{{ repository.name }}.local"
  loop: "{{ cvmfs_domains }}"
  loop_control:
    loop_var: repository
