---
# tasks file for hephy.cvmfs-client
- name: Load OS specific vars
  include_vars: "{{ item }}"
  first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version}}.yaml"
    - "{{ ansible_os_family }}.yaml"

- name: Enable CVMFS repository
  include_tasks: cvmfs-yumrepo.yml
  when: cvmfs_manage_repo

- name: Install cvmfs
  package:
    name: cvmfs
    state: installed

- name: Create /cvmfs
  file:
    name: /cvmfs
    state: directory

- name: Create CVMFS user and group
  block:
    - group:
        name: cvmfs
        system: true
    - user:
        name: cvmfs
        group: cvmfs
        groups: fuse
        system: true
        home: /var/lib/cvmfs
        shell: /sbin/nologin
        comment: "CernVM-FS service account"
  when: cvmfs_manage_user

- name: Set permission for home dir
  file:
    name: /var/lib/cvmfs
    owner: cvmfs
    group: cvmfs

- name: Configure autofs
  block:
    - lineinfile:
        path: /etc/auto.master
        regexp: "^/cvmfs"
        line: "/cvmfs  program:/etc/auto.cvmfs"
      notify: restart autofs
    - service:
        name: autofs
        enabled: true
        state: started
  when: cvmfs_manage_autofs
