---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: ${MOLECULE_IMAGE:-centos:7}
    privileged: true
    # devices:
    #   - /dev/fuse
    # capabilities:
    #   - SYS_ADMIN
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    W: ignore::DeprecationWarning
    junit-xml: ../../default_junit.xml
  lint:
    name: flake8
